In [11]:
import torch
import torch.nn.functional as F

In [12]:
x = torch.ones(1, requires_grad=True)
w = torch.full([1], 2, requires_grad=True)

In [13]:
print(x)

tensor([1.], requires_grad=True)


In [14]:
print(w)

tensor([2.], requires_grad=True)


In [15]:
b = torch.ones(1)

In [16]:
mse = F.mse_loss(x * w + b, torch.ones(1))
print(mse)

tensor(4., grad_fn=<MseLossBackward>)


In [7]:
torch.autograd.grad(mse, [w, x])

(tensor([4.]), tensor([8.]))

In [8]:
w.grad

In [9]:
x.grad

In [17]:
mse.backward()

In [18]:
x.grad

tensor([8.])

In [19]:
w.grad

tensor([4.])